#!/usr/bin/env python3

"""
Module to compute a specific summation
"""

def sigma_sum(start=2, end=5):
    """
    Compute the sum from start to end (inclusive)
    
    Args:
        start (int): starting integer (default 2)
        end (int): ending integer (default 5)
    
    Returns:
        int: The computed summation value
    """
    return sum(range(start, end + 1))


if __name__ == "__main__":
    print(sigma_sum())
